---
title: "Data Cleaning Script"
format: html
---

# Libraries and Packages

```{r packages}
install.packages("tidyverse")
install.packages("sentimentr")
library(tidyverse)
library(sentimentr)
```

# Load Data Sets

Load in data sets from import data folder

```{r}
#laod in wsj_data
read_csv("../data/imported_data/full_wsj_data.csv") ->
  wsj_data

#load in spy_data
read_csv("../data/imported_data/spy_data.csv") ->
  spy_data

#load in pe_data
read_csv("../data/imported_data/pe_ratio.csv") -> 
  pe_data
```

# WSJ Data

Cleaning WSJ data to extract data from URL and add in sentiment score

```{r}
#extract data from url column
wsj_data |>
  mutate(date = parse_date_time(str_extract(
    wsj_data$url, 
    pattern = "[0-9][0-9][0-9][0-9]/[0-9][0-9]/[0-9][0-9]"),
    orders = "ymd")) ->
  wsj_data


#add sentiment scores utilizing sentimentr::sentiment() function
wsj_data |>
  mutate(sentiment = sentiment_by(headlines)) ->
  wsj_data_sent

#remove unneeded columns
wsj_data_sent |>
  unnest_wider(sentiment) |>
  select(-element_id, -word_count, -sd) |>
  rename(sentiment = ave_sentiment) ->
  wsj_data_sent


#save new csv file to cleaned file
write_csv(x = wsj_data_sent,
          file = "../data/cleaned_data/wsj_data_sent.csv")
```

# P/E Data

Take monthly data and create daily by extracting the earnings and then creating daily PE from price changes

```{r}
#making date variable 
pe_data |> 
  mutate(month = month(date),
         year = year(date)) ->
  pe_data

#get price on first day of month to find earnings
spy_data |>
  mutate(date = parse_date_time(date, orders = "mdy")) |>
  mutate(month = month(date),
         year = year(date)) |>
  inner_join(pe_data, by = c("month", "year")) |>
  group_by(year, month) |>
  arrange(date.x, .by_group = TRUE) |>
  slice(1) |>
  mutate(earnings = price/pe_ratio) |>
  select(month, year, earnings) |>
  inner_join(pe_data, by = c("month", "year")) ->
  pe_data

#save new csv file to cleaned file
write_csv(x = pe_data,
          file = "../data/cleaned_data/pe_data.csv")
```

# SPY Data

Add sentiment and pe_ratio data to spy_data

```{r}
#get daily sentiment from wsj_data_sent
wsj_data_sent |>
  group_by(date) |>
  summarise(daily_sent = mean(sentiment)) |>
  select(date, daily_sent) ->
  daily_sent

#clean percentage change to numeric
spy_data |>
  mutate(change_percent = parse_number(change_percent)/100) ->
  spy_data

#add pe_ratio
spy_data |>
  mutate(date = parse_date_time(date, orders = "mdy")) |>
  inner_join(daily_sent, by = c("date")) |>
  mutate(month = month(date),
         year = year(date)) |>
  inner_join(pe_data, by = c("month", "year")) |>
  mutate(pe_ratio = price/earnings) |>
  select(-date.y, -month, -year, -earnings) |>
  rename(date = date.x) -> full_data

#write full data to cleaned
write_csv(x = full_data,
          file = "../data/cleaned_data/full_data.csv")
```
